---
- name: Installing and starting nginx
  hosts: slave
  become: yes
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:

    - name: updating the package
      apt:
        update_cache: yes

    - name: dynamic package
      apt:
        name: "{{ package_name }}"
        state: present

    - name: starting dynamic package
      service:
        name: "{{package_name}}"
        state: started

    - name: installing nginx
      apt:
        name: nginx
        state: latest
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

